### PR TITLE
Polish translation + few tweaks (language.csv)

### PR DESCRIPTION
**Pull request by justtoask**
added all strings in Polish
removed all the duplicate strings as they should be unnecessary (if the English string is the same as the translated one they should be left blank)
corrected a typo in the level Twilight Desolation (it was Desolution before)

### CODE REVIEW

**Comment by Owlet7** [comment]
Could you please restore the "unnecessary" strings? Those were kept in place to make comparisons with GZDoom's own localisation file easier.

**Comment by justtoask** [comment]
sure

**Comment by Owlet7** [comment]
Also, I'm sure Io is also called Io in Polish, not Lo?

**Comment by justtoask** [comment]
oh I confused the uppercase I with lowercase l lmao

**Comment by Owlet7** [comment]
You added some "unnecessary" strings that weren't originally there, but never mind, I'll fix it myself. Thanks!

**Pull request merged**
